packages:
  - "apps/*"
  - "functions/*"
  - "packages/*"

allowBuilds:
  esbuild: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@rollup/rollup-*"
  - "@tailwindcss/oxide-*"
trustPolicy: no-downgrade
trustPolicyExclude:
  - "semver"
