export type EncodeMode = "named" | "decimal" | "hex";

const NAMED_ENTITIES: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&apos;",
  "\u00A0": "&nbsp;",
  "\u00A1": "&iexcl;",
  "\u00A2": "&cent;",
  "\u00A3": "&pound;",
  "\u00A4": "&curren;",
  "\u00A5": "&yen;",
  "\u00A6": "&brvbar;",
  "\u00A7": "&sect;",
  "\u00A8": "&uml;",
  "\u00A9": "&copy;",
  "\u00AA": "&ordf;",
  "\u00AB": "&laquo;",
  "\u00AC": "&not;",
  "\u00AD": "&shy;",
  "\u00AE": "&reg;",
  "\u00AF": "&macr;",
  "\u00B0": "&deg;",
  "\u00B1": "&plusmn;",
  "\u00B2": "&sup2;",
  "\u00B3": "&sup3;",
  "\u00B4": "&acute;",
  "\u00B5": "&micro;",
  "\u00B6": "&para;",
  "\u00B7": "&middot;",
  "\u00B8": "&cedil;",
  "\u00B9": "&sup1;",
  "\u00BA": "&ordm;",
  "\u00BB": "&raquo;",
  "\u00BC": "&frac14;",
  "\u00BD": "&frac12;",
  "\u00BE": "&frac34;",
  "\u00BF": "&iquest;",
  "\u00D7": "&times;",
  "\u00F7": "&divide;",
  "\u2013": "&ndash;",
  "\u2014": "&mdash;",
  "\u2018": "&lsquo;",
  "\u2019": "&rsquo;",
  "\u201A": "&sbquo;",
  "\u201C": "&ldquo;",
  "\u201D": "&rdquo;",
  "\u201E": "&bdquo;",
  "\u2020": "&dagger;",
  "\u2021": "&Dagger;",
  "\u2022": "&bull;",
  "\u2026": "&hellip;",
  "\u2030": "&permil;",
  "\u2032": "&prime;",
  "\u2033": "&Prime;",
  "\u2039": "&lsaquo;",
  "\u203A": "&rsaquo;",
  "\u20AC": "&euro;",
  "\u2122": "&trade;",
  "\u2190": "&larr;",
  "\u2191": "&uarr;",
  "\u2192": "&rarr;",
  "\u2193": "&darr;",
  "\u2194": "&harr;",
  "\u221E": "&infin;",
  "\u2264": "&le;",
  "\u2265": "&ge;",
  "\u2660": "&spades;",
  "\u2663": "&clubs;",
  "\u2665": "&hearts;",
  "\u2666": "&diams;",
};

const NAMED_DECODE: Record<string, string> = Object.fromEntries(
  Object.entries(NAMED_ENTITIES).map(([char, entity]) => [
    entity.slice(1, -1),
    char,
  ]),
);

export function encodeHtml(input: string, mode: EncodeMode): string {
  let result = "";
  for (const char of input) {
    const code = char.codePointAt(0)!;

    if (mode === "named") {
      if (NAMED_ENTITIES[char]) {
        result += NAMED_ENTITIES[char];
      } else if (code > 127) {
        result += `&#${code};`;
      } else {
        result += char;
      }
    } else if (mode === "decimal") {
      if (char === "&") {
        result += "&amp;";
      } else if (char === "<") {
        result += "&lt;";
      } else if (char === ">") {
        result += "&gt;";
      } else if (char === '"') {
        result += "&quot;";
      } else if (char === "'") {
        result += "&apos;";
      } else if (code > 127) {
        result += `&#${code};`;
      } else {
        result += char;
      }
    } else {
      if (char === "&") {
        result += "&amp;";
      } else if (char === "<") {
        result += "&lt;";
      } else if (char === ">") {
        result += "&gt;";
      } else if (char === '"') {
        result += "&quot;";
      } else if (char === "'") {
        result += "&apos;";
      } else if (code > 127) {
        result += `&#x${code.toString(16)};`;
      } else {
        result += char;
      }
    }
  }
  return result;
}

const ENTITY_RE = /&(#[xX][0-9a-fA-F]+|#[0-9]+|[a-zA-Z][a-zA-Z0-9]*);/g;

export function decodeHtml(input: string): {
  output: string;
  error: string | null;
} {
  let hasInvalid = false;
  const output = input.replace(ENTITY_RE, (match, body: string) => {
    if (body[0] === "#") {
      let code: number;
      if (body[1] === "x" || body[1] === "X") {
        code = parseInt(body.slice(2), 16);
      } else {
        code = parseInt(body.slice(1), 10);
      }
      if (isNaN(code) || code < 0 || code > 0x10ffff) {
        hasInvalid = true;
        return match;
      }
      try {
        return String.fromCodePoint(code);
      } catch {
        hasInvalid = true;
        return match;
      }
    }
    const decoded = NAMED_DECODE[body.toLowerCase()];
    if (decoded !== undefined) return decoded;
    const decodedExact = NAMED_DECODE[body];
    if (decodedExact !== undefined) return decodedExact;
    hasInvalid = true;
    return match;
  });

  return hasInvalid
    ? { output, error: "Some entities could not be decoded" }
    : { output, error: null };
}

export interface EntityEntry {
  char: string;
  name: string | null;
  decimal: string;
  hex: string;
  description: string;
  category: string;
}

export const ENTITIES: EntityEntry[] = [
  {
    char: "&",
    name: "amp",
    decimal: "&#38;",
    hex: "&#x26;",
    description: "Ampersand",
    category: "Punctuation",
  },
  {
    char: "<",
    name: "lt",
    decimal: "&#60;",
    hex: "&#x3C;",
    description: "Less-than sign",
    category: "Punctuation",
  },
  {
    char: ">",
    name: "gt",
    decimal: "&#62;",
    hex: "&#x3E;",
    description: "Greater-than sign",
    category: "Punctuation",
  },
  {
    char: '"',
    name: "quot",
    decimal: "&#34;",
    hex: "&#x22;",
    description: "Quotation mark",
    category: "Punctuation",
  },
  {
    char: "'",
    name: "apos",
    decimal: "&#39;",
    hex: "&#x27;",
    description: "Apostrophe",
    category: "Punctuation",
  },
  {
    char: "\u00A0",
    name: "nbsp",
    decimal: "&#160;",
    hex: "&#xA0;",
    description: "Non-breaking space",
    category: "Punctuation",
  },
  {
    char: "\u00A1",
    name: "iexcl",
    decimal: "&#161;",
    hex: "&#xA1;",
    description: "Inverted exclamation mark",
    category: "Punctuation",
  },
  {
    char: "\u00A6",
    name: "brvbar",
    decimal: "&#166;",
    hex: "&#xA6;",
    description: "Broken bar (vertical bar)",
    category: "Punctuation",
  },
  {
    char: "\u00AB",
    name: "laquo",
    decimal: "&#171;",
    hex: "&#xAB;",
    description: "Left-pointing double angle quote",
    category: "Punctuation",
  },
  {
    char: "\u00BB",
    name: "raquo",
    decimal: "&#187;",
    hex: "&#xBB;",
    description: "Right-pointing double angle quote",
    category: "Punctuation",
  },
  {
    char: "\u00BF",
    name: "iquest",
    decimal: "&#191;",
    hex: "&#xBF;",
    description: "Inverted question mark",
    category: "Punctuation",
  },
  {
    char: "\u2013",
    name: "ndash",
    decimal: "&#8211;",
    hex: "&#x2013;",
    description: "En dash",
    category: "Typography",
  },
  {
    char: "\u2014",
    name: "mdash",
    decimal: "&#8212;",
    hex: "&#x2014;",
    description: "Em dash",
    category: "Typography",
  },
  {
    char: "\u2018",
    name: "lsquo",
    decimal: "&#8216;",
    hex: "&#x2018;",
    description: "Left single quote",
    category: "Typography",
  },
  {
    char: "\u2019",
    name: "rsquo",
    decimal: "&#8217;",
    hex: "&#x2019;",
    description: "Right single quote",
    category: "Typography",
  },
  {
    char: "\u201A",
    name: "sbquo",
    decimal: "&#8218;",
    hex: "&#x201A;",
    description: "Single low-9 quote",
    category: "Typography",
  },
  {
    char: "\u201C",
    name: "ldquo",
    decimal: "&#8220;",
    hex: "&#x201C;",
    description: "Left double quote",
    category: "Typography",
  },
  {
    char: "\u201D",
    name: "rdquo",
    decimal: "&#8221;",
    hex: "&#x201D;",
    description: "Right double quote",
    category: "Typography",
  },
  {
    char: "\u201E",
    name: "bdquo",
    decimal: "&#8222;",
    hex: "&#x201E;",
    description: "Double low-9 quote",
    category: "Typography",
  },
  {
    char: "\u2020",
    name: "dagger",
    decimal: "&#8224;",
    hex: "&#x2020;",
    description: "Dagger",
    category: "Typography",
  },
  {
    char: "\u2021",
    name: "Dagger",
    decimal: "&#8225;",
    hex: "&#x2021;",
    description: "Double dagger",
    category: "Typography",
  },
  {
    char: "\u2022",
    name: "bull",
    decimal: "&#8226;",
    hex: "&#x2022;",
    description: "Bullet",
    category: "Typography",
  },
  {
    char: "\u2026",
    name: "hellip",
    decimal: "&#8230;",
    hex: "&#x2026;",
    description: "Horizontal ellipsis",
    category: "Typography",
  },
  {
    char: "\u2030",
    name: "permil",
    decimal: "&#8240;",
    hex: "&#x2030;",
    description: "Per mille sign",
    category: "Typography",
  },
  {
    char: "\u2032",
    name: "prime",
    decimal: "&#8242;",
    hex: "&#x2032;",
    description: "Prime (minutes/feet)",
    category: "Typography",
  },
  {
    char: "\u2033",
    name: "Prime",
    decimal: "&#8243;",
    hex: "&#x2033;",
    description: "Double prime (seconds/inches)",
    category: "Typography",
  },
  {
    char: "\u2039",
    name: "lsaquo",
    decimal: "&#8249;",
    hex: "&#x2039;",
    description: "Single left angle quote",
    category: "Typography",
  },
  {
    char: "\u203A",
    name: "rsaquo",
    decimal: "&#8250;",
    hex: "&#x203A;",
    description: "Single right angle quote",
    category: "Typography",
  },
  {
    char: "\u00A2",
    name: "cent",
    decimal: "&#162;",
    hex: "&#xA2;",
    description: "Cent sign",
    category: "Currency",
  },
  {
    char: "\u00A3",
    name: "pound",
    decimal: "&#163;",
    hex: "&#xA3;",
    description: "Pound sign",
    category: "Currency",
  },
  {
    char: "\u00A4",
    name: "curren",
    decimal: "&#164;",
    hex: "&#xA4;",
    description: "Currency sign",
    category: "Currency",
  },
  {
    char: "\u00A5",
    name: "yen",
    decimal: "&#165;",
    hex: "&#xA5;",
    description: "Yen sign",
    category: "Currency",
  },
  {
    char: "\u20AC",
    name: "euro",
    decimal: "&#8364;",
    hex: "&#x20AC;",
    description: "Euro sign",
    category: "Currency",
  },
  {
    char: "\u00A7",
    name: "sect",
    decimal: "&#167;",
    hex: "&#xA7;",
    description: "Section sign",
    category: "Punctuation",
  },
  {
    char: "\u00A8",
    name: "uml",
    decimal: "&#168;",
    hex: "&#xA8;",
    description: "Diaeresis (umlaut)",
    category: "Punctuation",
  },
  {
    char: "\u00A9",
    name: "copy",
    decimal: "&#169;",
    hex: "&#xA9;",
    description: "Copyright sign",
    category: "Symbols",
  },
  {
    char: "\u00AE",
    name: "reg",
    decimal: "&#174;",
    hex: "&#xAE;",
    description: "Registered sign",
    category: "Symbols",
  },
  {
    char: "\u2122",
    name: "trade",
    decimal: "&#8482;",
    hex: "&#x2122;",
    description: "Trademark sign",
    category: "Symbols",
  },
  {
    char: "\u00AF",
    name: "macr",
    decimal: "&#175;",
    hex: "&#xAF;",
    description: "Macron",
    category: "Punctuation",
  },
  {
    char: "\u00B0",
    name: "deg",
    decimal: "&#176;",
    hex: "&#xB0;",
    description: "Degree sign",
    category: "Symbols",
  },
  {
    char: "\u00B1",
    name: "plusmn",
    decimal: "&#177;",
    hex: "&#xB1;",
    description: "Plus-minus sign",
    category: "Math",
  },
  {
    char: "\u00B2",
    name: "sup2",
    decimal: "&#178;",
    hex: "&#xB2;",
    description: "Superscript two",
    category: "Math",
  },
  {
    char: "\u00B3",
    name: "sup3",
    decimal: "&#179;",
    hex: "&#xB3;",
    description: "Superscript three",
    category: "Math",
  },
  {
    char: "\u00B4",
    name: "acute",
    decimal: "&#180;",
    hex: "&#xB4;",
    description: "Acute accent",
    category: "Punctuation",
  },
  {
    char: "\u00B5",
    name: "micro",
    decimal: "&#181;",
    hex: "&#xB5;",
    description: "Micro sign",
    category: "Math",
  },
  {
    char: "\u00B6",
    name: "para",
    decimal: "&#182;",
    hex: "&#xB6;",
    description: "Pilcrow (paragraph mark)",
    category: "Punctuation",
  },
  {
    char: "\u00B7",
    name: "middot",
    decimal: "&#183;",
    hex: "&#xB7;",
    description: "Middle dot",
    category: "Punctuation",
  },
  {
    char: "\u00B8",
    name: "cedil",
    decimal: "&#184;",
    hex: "&#xB8;",
    description: "Cedilla",
    category: "Punctuation",
  },
  {
    char: "\u00B9",
    name: "sup1",
    decimal: "&#185;",
    hex: "&#xB9;",
    description: "Superscript one",
    category: "Math",
  },
  {
    char: "\u00BC",
    name: "frac14",
    decimal: "&#188;",
    hex: "&#xBC;",
    description: "Fraction one quarter",
    category: "Math",
  },
  {
    char: "\u00BD",
    name: "frac12",
    decimal: "&#189;",
    hex: "&#xBD;",
    description: "Fraction one half",
    category: "Math",
  },
  {
    char: "\u00BE",
    name: "frac34",
    decimal: "&#190;",
    hex: "&#xBE;",
    description: "Fraction three quarters",
    category: "Math",
  },
  {
    char: "\u00D7",
    name: "times",
    decimal: "&#215;",
    hex: "&#xD7;",
    description: "Multiplication sign",
    category: "Math",
  },
  {
    char: "\u00F7",
    name: "divide",
    decimal: "&#247;",
    hex: "&#xF7;",
    description: "Division sign",
    category: "Math",
  },
  {
    char: "\u00AC",
    name: "not",
    decimal: "&#172;",
    hex: "&#xAC;",
    description: "Not sign",
    category: "Math",
  },
  {
    char: "\u221E",
    name: "infin",
    decimal: "&#8734;",
    hex: "&#x221E;",
    description: "Infinity",
    category: "Math",
  },
  {
    char: "\u2264",
    name: "le",
    decimal: "&#8804;",
    hex: "&#x2264;",
    description: "Less-than or equal to",
    category: "Math",
  },
  {
    char: "\u2265",
    name: "ge",
    decimal: "&#8805;",
    hex: "&#x2265;",
    description: "Greater-than or equal to",
    category: "Math",
  },
  {
    char: "\u2260",
    name: null,
    decimal: "&#8800;",
    hex: "&#x2260;",
    description: "Not equal to",
    category: "Math",
  },
  {
    char: "\u2248",
    name: null,
    decimal: "&#8776;",
    hex: "&#x2248;",
    description: "Almost equal to (asymptotic)",
    category: "Math",
  },
  {
    char: "\u2211",
    name: "sum",
    decimal: "&#8721;",
    hex: "&#x2211;",
    description: "N-ary summation",
    category: "Math",
  },
  {
    char: "\u220F",
    name: "prod",
    decimal: "&#8719;",
    hex: "&#x220F;",
    description: "N-ary product",
    category: "Math",
  },
  {
    char: "\u221A",
    name: null,
    decimal: "&#8730;",
    hex: "&#x221A;",
    description: "Square root",
    category: "Math",
  },
  {
    char: "\u2202",
    name: "part",
    decimal: "&#8706;",
    hex: "&#x2202;",
    description: "Partial differential",
    category: "Math",
  },
  {
    char: "\u222B",
    name: null,
    decimal: "&#8747;",
    hex: "&#x222B;",
    description: "Integral",
    category: "Math",
  },
  {
    char: "\u2208",
    name: "isin",
    decimal: "&#8712;",
    hex: "&#x2208;",
    description: "Element of",
    category: "Math",
  },
  {
    char: "\u2209",
    name: "notin",
    decimal: "&#8713;",
    hex: "&#x2209;",
    description: "Not an element of",
    category: "Math",
  },
  {
    char: "\u2282",
    name: "sub",
    decimal: "&#8834;",
    hex: "&#x2282;",
    description: "Subset of",
    category: "Math",
  },
  {
    char: "\u2283",
    name: "sup",
    decimal: "&#8835;",
    hex: "&#x2283;",
    description: "Superset of",
    category: "Math",
  },
  {
    char: "\u2229",
    name: "cap",
    decimal: "&#8745;",
    hex: "&#x2229;",
    description: "Intersection",
    category: "Math",
  },
  {
    char: "\u222A",
    name: "cup",
    decimal: "&#8746;",
    hex: "&#x222A;",
    description: "Union",
    category: "Math",
  },
  {
    char: "\u2190",
    name: "larr",
    decimal: "&#8592;",
    hex: "&#x2190;",
    description: "Leftwards arrow",
    category: "Arrows",
  },
  {
    char: "\u2191",
    name: "uarr",
    decimal: "&#8593;",
    hex: "&#x2191;",
    description: "Upwards arrow",
    category: "Arrows",
  },
  {
    char: "\u2192",
    name: "rarr",
    decimal: "&#8594;",
    hex: "&#x2192;",
    description: "Rightwards arrow",
    category: "Arrows",
  },
  {
    char: "\u2193",
    name: "darr",
    decimal: "&#8595;",
    hex: "&#x2193;",
    description: "Downwards arrow",
    category: "Arrows",
  },
  {
    char: "\u2194",
    name: "harr",
    decimal: "&#8596;",
    hex: "&#x2194;",
    description: "Left right arrow",
    category: "Arrows",
  },
  {
    char: "\u21A6",
    name: null,
    decimal: "&#8678;",
    hex: "&#x21A6;",
    description: "Rightwards arrow from bar (maps to)",
    category: "Arrows",
  },
  {
    char: "\u21D0",
    name: null,
    decimal: "&#8656;",
    hex: "&#x21D0;",
    description: "Leftwards double arrow",
    category: "Arrows",
  },
  {
    char: "\u21D1",
    name: null,
    decimal: "&#8657;",
    hex: "&#x21D1;",
    description: "Upwards double arrow",
    category: "Arrows",
  },
  {
    char: "\u21D2",
    name: null,
    decimal: "&#8658;",
    hex: "&#x21D2;",
    description: "Rightwards double arrow (implies)",
    category: "Arrows",
  },
  {
    char: "\u21D3",
    name: null,
    decimal: "&#8659;",
    hex: "&#x21D3;",
    description: "Downwards double arrow",
    category: "Arrows",
  },
  {
    char: "\u21D4",
    name: null,
    decimal: "&#8660;",
    hex: "&#x21D4;",
    description: "Left right double arrow (iff)",
    category: "Arrows",
  },
  {
    char: "\u2660",
    name: "spades",
    decimal: "&#9824;",
    hex: "&#x2660;",
    description: "Black spade suit",
    category: "Symbols",
  },
  {
    char: "\u2663",
    name: "clubs",
    decimal: "&#9827;",
    hex: "&#x2663;",
    description: "Black club suit",
    category: "Symbols",
  },
  {
    char: "\u2665",
    name: "hearts",
    decimal: "&#9829;",
    hex: "&#x2665;",
    description: "Black heart suit",
    category: "Symbols",
  },
  {
    char: "\u2666",
    name: "diams",
    decimal: "&#9830;",
    hex: "&#x2666;",
    description: "Black diamond suit",
    category: "Symbols",
  },
  {
    char: "\u00AA",
    name: "ordf",
    decimal: "&#170;",
    hex: "&#xAA;",
    description: "Feminine ordinal indicator",
    category: "Typography",
  },
  {
    char: "\u00BA",
    name: "ordm",
    decimal: "&#186;",
    hex: "&#xBA;",
    description: "Masculine ordinal indicator",
    category: "Typography",
  },
  {
    char: "\u00C0",
    name: "Agrave",
    decimal: "&#192;",
    hex: "&#xC0;",
    description: "A with grave",
    category: "Letters",
  },
  {
    char: "\u00C1",
    name: "Aacute",
    decimal: "&#193;",
    hex: "&#xC1;",
    description: "A with acute",
    category: "Letters",
  },
  {
    char: "\u00C2",
    name: "Acirc",
    decimal: "&#194;",
    hex: "&#xC2;",
    description: "A with circumflex",
    category: "Letters",
  },
  {
    char: "\u00C3",
    name: "Atilde",
    decimal: "&#195;",
    hex: "&#xC3;",
    description: "A with tilde",
    category: "Letters",
  },
  {
    char: "\u00C4",
    name: "Auml",
    decimal: "&#196;",
    hex: "&#xC4;",
    description: "A with diaeresis",
    category: "Letters",
  },
  {
    char: "\u00C5",
    name: "Aring",
    decimal: "&#197;",
    hex: "&#xC5;",
    description: "A with ring above",
    category: "Letters",
  },
  {
    char: "\u00C6",
    name: "AElig",
    decimal: "&#198;",
    hex: "&#xC6;",
    description: "AE ligature",
    category: "Letters",
  },
  {
    char: "\u00C7",
    name: "Acedil",
    decimal: "&#199;",
    hex: "&#xC7;",
    description: "C with cedilla",
    category: "Letters",
  },
  {
    char: "\u00C8",
    name: "Egrave",
    decimal: "&#200;",
    hex: "&#xC8;",
    description: "E with grave",
    category: "Letters",
  },
  {
    char: "\u00C9",
    name: "Eacute",
    decimal: "&#201;",
    hex: "&#xC9;",
    description: "E with acute",
    category: "Letters",
  },
  {
    char: "\u00CA",
    name: "Ecirc",
    decimal: "&#202;",
    hex: "&#xCA;",
    description: "E with circumflex",
    category: "Letters",
  },
  {
    char: "\u00CB",
    name: "Euml",
    decimal: "&#203;",
    hex: "&#xCB;",
    description: "E with diaeresis",
    category: "Letters",
  },
  {
    char: "\u00CC",
    name: "Igrave",
    decimal: "&#204;",
    hex: "&#xCC;",
    description: "I with grave",
    category: "Letters",
  },
  {
    char: "\u00CD",
    name: "Iacute",
    decimal: "&#205;",
    hex: "&#xCD;",
    description: "I with acute",
    category: "Letters",
  },
  {
    char: "\u00CE",
    name: "Icirc",
    decimal: "&#206;",
    hex: "&#xCE;",
    description: "I with circumflex",
    category: "Letters",
  },
  {
    char: "\u00CF",
    name: "Iuml",
    decimal: "&#207;",
    hex: "&#xCF;",
    description: "I with diaeresis",
    category: "Letters",
  },
  {
    char: "\u00D1",
    name: "Ntilde",
    decimal: "&#209;",
    hex: "&#xD1;",
    description: "N with tilde",
    category: "Letters",
  },
  {
    char: "\u00D2",
    name: "Ograve",
    decimal: "&#210;",
    hex: "&#xD2;",
    description: "O with grave",
    category: "Letters",
  },
  {
    char: "\u00D3",
    name: "Oacute",
    decimal: "&#211;",
    hex: "&#xD3;",
    description: "O with acute",
    category: "Letters",
  },
  {
    char: "\u00D4",
    name: "Ocirc",
    decimal: "&#212;",
    hex: "&#xD4;",
    description: "O with circumflex",
    category: "Letters",
  },
  {
    char: "\u00D5",
    name: "Otilde",
    decimal: "&#213;",
    hex: "&#xD5;",
    description: "O with tilde",
    category: "Letters",
  },
  {
    char: "\u00D6",
    name: "Ouml",
    decimal: "&#214;",
    hex: "&#xD6;",
    description: "O with diaeresis",
    category: "Letters",
  },
  {
    char: "\u00D8",
    name: "Oslash",
    decimal: "&#216;",
    hex: "&#xD8;",
    description: "O with stroke",
    category: "Letters",
  },
  {
    char: "\u00D9",
    name: "Ugrave",
    decimal: "&#217;",
    hex: "&#xD9;",
    description: "U with grave",
    category: "Letters",
  },
  {
    char: "\u00DA",
    name: "Uacute",
    decimal: "&#218;",
    hex: "&#xDA;",
    description: "U with acute",
    category: "Letters",
  },
  {
    char: "\u00DB",
    name: "Ucirc",
    decimal: "&#219;",
    hex: "&#xDB;",
    description: "U with circumflex",
    category: "Letters",
  },
  {
    char: "\u00DC",
    name: "Uuml",
    decimal: "&#220;",
    hex: "&#xDC;",
    description: "U with diaeresis",
    category: "Letters",
  },
  {
    char: "\u00DF",
    name: "szlig",
    decimal: "&#223;",
    hex: "&#xDF;",
    description: "Sharp s (eszett)",
    category: "Letters",
  },
  {
    char: "\u00E0",
    name: "agrave",
    decimal: "&#224;",
    hex: "&#xE0;",
    description: "a with grave",
    category: "Letters",
  },
  {
    char: "\u00E1",
    name: "aacute",
    decimal: "&#225;",
    hex: "&#xE1;",
    description: "a with acute",
    category: "Letters",
  },
  {
    char: "\u00E9",
    name: "eacute",
    decimal: "&#233;",
    hex: "&#xE9;",
    description: "e with acute",
    category: "Letters",
  },
  {
    char: "\u00F1",
    name: "ntilde",
    decimal: "&#241;",
    hex: "&#xF1;",
    description: "n with tilde",
    category: "Letters",
  },
  {
    char: "\u00FC",
    name: "uuml",
    decimal: "&#252;",
    hex: "&#xFC;",
    description: "u with diaeresis",
    category: "Letters",
  },
  {
    char: "\u2605",
    name: null,
    decimal: "&#9733;",
    hex: "&#x2605;",
    description: "Black star",
    category: "Symbols",
  },
  {
    char: "\u2606",
    name: null,
    decimal: "&#9734;",
    hex: "&#x2606;",
    description: "White star",
    category: "Symbols",
  },
  {
    char: "\u2610",
    name: null,
    decimal: "&#9744;",
    hex: "&#x2610;",
    description: "Ballot box (empty checkbox)",
    category: "Symbols",
  },
  {
    char: "\u2611",
    name: null,
    decimal: "&#9745;",
    hex: "&#x2611;",
    description: "Ballot box with check",
    category: "Symbols",
  },
  {
    char: "\u2612",
    name: null,
    decimal: "&#9746;",
    hex: "&#x2612;",
    description: "Ballot box with X",
    category: "Symbols",
  },
  {
    char: "\u263A",
    name: null,
    decimal: "&#9786;",
    hex: "&#x263A;",
    description: "White smiling face",
    category: "Symbols",
  },
  {
    char: "\u263B",
    name: null,
    decimal: "&#9787;",
    hex: "&#x263B;",
    description: "Black smiling face",
    category: "Symbols",
  },
  {
    char: "\u2705",
    name: null,
    decimal: "&#9989;",
    hex: "&#x2705;",
    description: "White heavy check mark",
    category: "Symbols",
  },
  {
    char: "\u2713",
    name: "check",
    decimal: "&#10003;",
    hex: "&#x2713;",
    description: "Check mark",
    category: "Symbols",
  },
  {
    char: "\u2717",
    name: null,
    decimal: "&#10007;",
    hex: "&#x2717;",
    description: "Ballot X",
    category: "Symbols",
  },
  {
    char: "\u2714",
    name: null,
    decimal: "&#10004;",
    hex: "&#x2714;",
    description: "Heavy check mark",
    category: "Symbols",
  },
  {
    char: "\u2718",
    name: null,
    decimal: "&#10008;",
    hex: "&#x2718;",
    description: "Heavy ballot X",
    category: "Symbols",
  },
  {
    char: "\u2728",
    name: null,
    decimal: "&#10024;",
    hex: "&#x2728;",
    description: "Sparkles",
    category: "Symbols",
  },
];
