/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUuidGeneratorRouteImport } from './routes/_authenticated/uuid-generator'
import { Route as AuthenticatedUrlEncoderRouteImport } from './routes/_authenticated/url-encoder'
import { Route as AuthenticatedTimestampConverterRouteImport } from './routes/_authenticated/timestamp-converter'
import { Route as AuthenticatedTextManipulatorRouteImport } from './routes/_authenticated/text-manipulator'
import { Route as AuthenticatedRegexTesterRouteImport } from './routes/_authenticated/regex-tester'
import { Route as AuthenticatedQrGeneratorRouteImport } from './routes/_authenticated/qr-generator'
import { Route as AuthenticatedLoremIpsumRouteImport } from './routes/_authenticated/lorem-ipsum'
import { Route as AuthenticatedJwtDecoderRouteImport } from './routes/_authenticated/jwt-decoder'
import { Route as AuthenticatedJsonToTypescriptRouteImport } from './routes/_authenticated/json-to-typescript'
import { Route as AuthenticatedJsonFormatterRouteImport } from './routes/_authenticated/json-formatter'
import { Route as AuthenticatedImageToolsRouteImport } from './routes/_authenticated/image-tools'
import { Route as AuthenticatedHttpTesterRouteImport } from './routes/_authenticated/http-tester'
import { Route as AuthenticatedHtmlEntitiesRouteImport } from './routes/_authenticated/html-entities'
import { Route as AuthenticatedHashGeneratorRouteImport } from './routes/_authenticated/hash-generator'
import { Route as AuthenticatedFormatConverterRouteImport } from './routes/_authenticated/format-converter'
import { Route as AuthenticatedFileValidatorRouteImport } from './routes/_authenticated/file-validator'
import { Route as AuthenticatedDiffToolRouteImport } from './routes/_authenticated/diff-tool'
import { Route as AuthenticatedDevBoardRouteImport } from './routes/_authenticated/dev-board'
import { Route as AuthenticatedColorConverterRouteImport } from './routes/_authenticated/color-converter'
import { Route as AuthenticatedBookmarksRouteImport } from './routes/_authenticated/bookmarks'
import { Route as AuthenticatedBase64RouteImport } from './routes/_authenticated/base64'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUuidGeneratorRoute =
  AuthenticatedUuidGeneratorRouteImport.update({
    id: '/uuid-generator',
    path: '/uuid-generator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUrlEncoderRoute = AuthenticatedUrlEncoderRouteImport.update({
  id: '/url-encoder',
  path: '/url-encoder',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimestampConverterRoute =
  AuthenticatedTimestampConverterRouteImport.update({
    id: '/timestamp-converter',
    path: '/timestamp-converter',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTextManipulatorRoute =
  AuthenticatedTextManipulatorRouteImport.update({
    id: '/text-manipulator',
    path: '/text-manipulator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRegexTesterRoute =
  AuthenticatedRegexTesterRouteImport.update({
    id: '/regex-tester',
    path: '/regex-tester',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQrGeneratorRoute =
  AuthenticatedQrGeneratorRouteImport.update({
    id: '/qr-generator',
    path: '/qr-generator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoremIpsumRoute = AuthenticatedLoremIpsumRouteImport.update({
  id: '/lorem-ipsum',
  path: '/lorem-ipsum',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJwtDecoderRoute = AuthenticatedJwtDecoderRouteImport.update({
  id: '/jwt-decoder',
  path: '/jwt-decoder',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJsonToTypescriptRoute =
  AuthenticatedJsonToTypescriptRouteImport.update({
    id: '/json-to-typescript',
    path: '/json-to-typescript',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJsonFormatterRoute =
  AuthenticatedJsonFormatterRouteImport.update({
    id: '/json-formatter',
    path: '/json-formatter',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImageToolsRoute = AuthenticatedImageToolsRouteImport.update({
  id: '/image-tools',
  path: '/image-tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHttpTesterRoute = AuthenticatedHttpTesterRouteImport.update({
  id: '/http-tester',
  path: '/http-tester',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHtmlEntitiesRoute =
  AuthenticatedHtmlEntitiesRouteImport.update({
    id: '/html-entities',
    path: '/html-entities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHashGeneratorRoute =
  AuthenticatedHashGeneratorRouteImport.update({
    id: '/hash-generator',
    path: '/hash-generator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormatConverterRoute =
  AuthenticatedFormatConverterRouteImport.update({
    id: '/format-converter',
    path: '/format-converter',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFileValidatorRoute =
  AuthenticatedFileValidatorRouteImport.update({
    id: '/file-validator',
    path: '/file-validator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDiffToolRoute = AuthenticatedDiffToolRouteImport.update({
  id: '/diff-tool',
  path: '/diff-tool',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevBoardRoute = AuthenticatedDevBoardRouteImport.update({
  id: '/dev-board',
  path: '/dev-board',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedColorConverterRoute =
  AuthenticatedColorConverterRouteImport.update({
    id: '/color-converter',
    path: '/color-converter',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookmarksRoute = AuthenticatedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBase64Route = AuthenticatedBase64RouteImport.update({
  id: '/base64',
  path: '/base64',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/base64': typeof AuthenticatedBase64Route
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/color-converter': typeof AuthenticatedColorConverterRoute
  '/dev-board': typeof AuthenticatedDevBoardRoute
  '/diff-tool': typeof AuthenticatedDiffToolRoute
  '/file-validator': typeof AuthenticatedFileValidatorRoute
  '/format-converter': typeof AuthenticatedFormatConverterRoute
  '/hash-generator': typeof AuthenticatedHashGeneratorRoute
  '/html-entities': typeof AuthenticatedHtmlEntitiesRoute
  '/http-tester': typeof AuthenticatedHttpTesterRoute
  '/image-tools': typeof AuthenticatedImageToolsRoute
  '/json-formatter': typeof AuthenticatedJsonFormatterRoute
  '/json-to-typescript': typeof AuthenticatedJsonToTypescriptRoute
  '/jwt-decoder': typeof AuthenticatedJwtDecoderRoute
  '/lorem-ipsum': typeof AuthenticatedLoremIpsumRoute
  '/qr-generator': typeof AuthenticatedQrGeneratorRoute
  '/regex-tester': typeof AuthenticatedRegexTesterRoute
  '/text-manipulator': typeof AuthenticatedTextManipulatorRoute
  '/timestamp-converter': typeof AuthenticatedTimestampConverterRoute
  '/url-encoder': typeof AuthenticatedUrlEncoderRoute
  '/uuid-generator': typeof AuthenticatedUuidGeneratorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/base64': typeof AuthenticatedBase64Route
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/color-converter': typeof AuthenticatedColorConverterRoute
  '/dev-board': typeof AuthenticatedDevBoardRoute
  '/diff-tool': typeof AuthenticatedDiffToolRoute
  '/file-validator': typeof AuthenticatedFileValidatorRoute
  '/format-converter': typeof AuthenticatedFormatConverterRoute
  '/hash-generator': typeof AuthenticatedHashGeneratorRoute
  '/html-entities': typeof AuthenticatedHtmlEntitiesRoute
  '/http-tester': typeof AuthenticatedHttpTesterRoute
  '/image-tools': typeof AuthenticatedImageToolsRoute
  '/json-formatter': typeof AuthenticatedJsonFormatterRoute
  '/json-to-typescript': typeof AuthenticatedJsonToTypescriptRoute
  '/jwt-decoder': typeof AuthenticatedJwtDecoderRoute
  '/lorem-ipsum': typeof AuthenticatedLoremIpsumRoute
  '/qr-generator': typeof AuthenticatedQrGeneratorRoute
  '/regex-tester': typeof AuthenticatedRegexTesterRoute
  '/text-manipulator': typeof AuthenticatedTextManipulatorRoute
  '/timestamp-converter': typeof AuthenticatedTimestampConverterRoute
  '/url-encoder': typeof AuthenticatedUrlEncoderRoute
  '/uuid-generator': typeof AuthenticatedUuidGeneratorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/base64': typeof AuthenticatedBase64Route
  '/_authenticated/bookmarks': typeof AuthenticatedBookmarksRoute
  '/_authenticated/color-converter': typeof AuthenticatedColorConverterRoute
  '/_authenticated/dev-board': typeof AuthenticatedDevBoardRoute
  '/_authenticated/diff-tool': typeof AuthenticatedDiffToolRoute
  '/_authenticated/file-validator': typeof AuthenticatedFileValidatorRoute
  '/_authenticated/format-converter': typeof AuthenticatedFormatConverterRoute
  '/_authenticated/hash-generator': typeof AuthenticatedHashGeneratorRoute
  '/_authenticated/html-entities': typeof AuthenticatedHtmlEntitiesRoute
  '/_authenticated/http-tester': typeof AuthenticatedHttpTesterRoute
  '/_authenticated/image-tools': typeof AuthenticatedImageToolsRoute
  '/_authenticated/json-formatter': typeof AuthenticatedJsonFormatterRoute
  '/_authenticated/json-to-typescript': typeof AuthenticatedJsonToTypescriptRoute
  '/_authenticated/jwt-decoder': typeof AuthenticatedJwtDecoderRoute
  '/_authenticated/lorem-ipsum': typeof AuthenticatedLoremIpsumRoute
  '/_authenticated/qr-generator': typeof AuthenticatedQrGeneratorRoute
  '/_authenticated/regex-tester': typeof AuthenticatedRegexTesterRoute
  '/_authenticated/text-manipulator': typeof AuthenticatedTextManipulatorRoute
  '/_authenticated/timestamp-converter': typeof AuthenticatedTimestampConverterRoute
  '/_authenticated/url-encoder': typeof AuthenticatedUrlEncoderRoute
  '/_authenticated/uuid-generator': typeof AuthenticatedUuidGeneratorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/base64'
    | '/bookmarks'
    | '/color-converter'
    | '/dev-board'
    | '/diff-tool'
    | '/file-validator'
    | '/format-converter'
    | '/hash-generator'
    | '/html-entities'
    | '/http-tester'
    | '/image-tools'
    | '/json-formatter'
    | '/json-to-typescript'
    | '/jwt-decoder'
    | '/lorem-ipsum'
    | '/qr-generator'
    | '/regex-tester'
    | '/text-manipulator'
    | '/timestamp-converter'
    | '/url-encoder'
    | '/uuid-generator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/base64'
    | '/bookmarks'
    | '/color-converter'
    | '/dev-board'
    | '/diff-tool'
    | '/file-validator'
    | '/format-converter'
    | '/hash-generator'
    | '/html-entities'
    | '/http-tester'
    | '/image-tools'
    | '/json-formatter'
    | '/json-to-typescript'
    | '/jwt-decoder'
    | '/lorem-ipsum'
    | '/qr-generator'
    | '/regex-tester'
    | '/text-manipulator'
    | '/timestamp-converter'
    | '/url-encoder'
    | '/uuid-generator'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/base64'
    | '/_authenticated/bookmarks'
    | '/_authenticated/color-converter'
    | '/_authenticated/dev-board'
    | '/_authenticated/diff-tool'
    | '/_authenticated/file-validator'
    | '/_authenticated/format-converter'
    | '/_authenticated/hash-generator'
    | '/_authenticated/html-entities'
    | '/_authenticated/http-tester'
    | '/_authenticated/image-tools'
    | '/_authenticated/json-formatter'
    | '/_authenticated/json-to-typescript'
    | '/_authenticated/jwt-decoder'
    | '/_authenticated/lorem-ipsum'
    | '/_authenticated/qr-generator'
    | '/_authenticated/regex-tester'
    | '/_authenticated/text-manipulator'
    | '/_authenticated/timestamp-converter'
    | '/_authenticated/url-encoder'
    | '/_authenticated/uuid-generator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/uuid-generator': {
      id: '/_authenticated/uuid-generator'
      path: '/uuid-generator'
      fullPath: '/uuid-generator'
      preLoaderRoute: typeof AuthenticatedUuidGeneratorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/url-encoder': {
      id: '/_authenticated/url-encoder'
      path: '/url-encoder'
      fullPath: '/url-encoder'
      preLoaderRoute: typeof AuthenticatedUrlEncoderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/timestamp-converter': {
      id: '/_authenticated/timestamp-converter'
      path: '/timestamp-converter'
      fullPath: '/timestamp-converter'
      preLoaderRoute: typeof AuthenticatedTimestampConverterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/text-manipulator': {
      id: '/_authenticated/text-manipulator'
      path: '/text-manipulator'
      fullPath: '/text-manipulator'
      preLoaderRoute: typeof AuthenticatedTextManipulatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/regex-tester': {
      id: '/_authenticated/regex-tester'
      path: '/regex-tester'
      fullPath: '/regex-tester'
      preLoaderRoute: typeof AuthenticatedRegexTesterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qr-generator': {
      id: '/_authenticated/qr-generator'
      path: '/qr-generator'
      fullPath: '/qr-generator'
      preLoaderRoute: typeof AuthenticatedQrGeneratorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lorem-ipsum': {
      id: '/_authenticated/lorem-ipsum'
      path: '/lorem-ipsum'
      fullPath: '/lorem-ipsum'
      preLoaderRoute: typeof AuthenticatedLoremIpsumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jwt-decoder': {
      id: '/_authenticated/jwt-decoder'
      path: '/jwt-decoder'
      fullPath: '/jwt-decoder'
      preLoaderRoute: typeof AuthenticatedJwtDecoderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/json-to-typescript': {
      id: '/_authenticated/json-to-typescript'
      path: '/json-to-typescript'
      fullPath: '/json-to-typescript'
      preLoaderRoute: typeof AuthenticatedJsonToTypescriptRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/json-formatter': {
      id: '/_authenticated/json-formatter'
      path: '/json-formatter'
      fullPath: '/json-formatter'
      preLoaderRoute: typeof AuthenticatedJsonFormatterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/image-tools': {
      id: '/_authenticated/image-tools'
      path: '/image-tools'
      fullPath: '/image-tools'
      preLoaderRoute: typeof AuthenticatedImageToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/http-tester': {
      id: '/_authenticated/http-tester'
      path: '/http-tester'
      fullPath: '/http-tester'
      preLoaderRoute: typeof AuthenticatedHttpTesterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/html-entities': {
      id: '/_authenticated/html-entities'
      path: '/html-entities'
      fullPath: '/html-entities'
      preLoaderRoute: typeof AuthenticatedHtmlEntitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hash-generator': {
      id: '/_authenticated/hash-generator'
      path: '/hash-generator'
      fullPath: '/hash-generator'
      preLoaderRoute: typeof AuthenticatedHashGeneratorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/format-converter': {
      id: '/_authenticated/format-converter'
      path: '/format-converter'
      fullPath: '/format-converter'
      preLoaderRoute: typeof AuthenticatedFormatConverterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/file-validator': {
      id: '/_authenticated/file-validator'
      path: '/file-validator'
      fullPath: '/file-validator'
      preLoaderRoute: typeof AuthenticatedFileValidatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diff-tool': {
      id: '/_authenticated/diff-tool'
      path: '/diff-tool'
      fullPath: '/diff-tool'
      preLoaderRoute: typeof AuthenticatedDiffToolRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dev-board': {
      id: '/_authenticated/dev-board'
      path: '/dev-board'
      fullPath: '/dev-board'
      preLoaderRoute: typeof AuthenticatedDevBoardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/color-converter': {
      id: '/_authenticated/color-converter'
      path: '/color-converter'
      fullPath: '/color-converter'
      preLoaderRoute: typeof AuthenticatedColorConverterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookmarks': {
      id: '/_authenticated/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthenticatedBookmarksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/base64': {
      id: '/_authenticated/base64'
      path: '/base64'
      fullPath: '/base64'
      preLoaderRoute: typeof AuthenticatedBase64RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBase64Route: typeof AuthenticatedBase64Route
  AuthenticatedBookmarksRoute: typeof AuthenticatedBookmarksRoute
  AuthenticatedColorConverterRoute: typeof AuthenticatedColorConverterRoute
  AuthenticatedDevBoardRoute: typeof AuthenticatedDevBoardRoute
  AuthenticatedDiffToolRoute: typeof AuthenticatedDiffToolRoute
  AuthenticatedFileValidatorRoute: typeof AuthenticatedFileValidatorRoute
  AuthenticatedFormatConverterRoute: typeof AuthenticatedFormatConverterRoute
  AuthenticatedHashGeneratorRoute: typeof AuthenticatedHashGeneratorRoute
  AuthenticatedHtmlEntitiesRoute: typeof AuthenticatedHtmlEntitiesRoute
  AuthenticatedHttpTesterRoute: typeof AuthenticatedHttpTesterRoute
  AuthenticatedImageToolsRoute: typeof AuthenticatedImageToolsRoute
  AuthenticatedJsonFormatterRoute: typeof AuthenticatedJsonFormatterRoute
  AuthenticatedJsonToTypescriptRoute: typeof AuthenticatedJsonToTypescriptRoute
  AuthenticatedJwtDecoderRoute: typeof AuthenticatedJwtDecoderRoute
  AuthenticatedLoremIpsumRoute: typeof AuthenticatedLoremIpsumRoute
  AuthenticatedQrGeneratorRoute: typeof AuthenticatedQrGeneratorRoute
  AuthenticatedRegexTesterRoute: typeof AuthenticatedRegexTesterRoute
  AuthenticatedTextManipulatorRoute: typeof AuthenticatedTextManipulatorRoute
  AuthenticatedTimestampConverterRoute: typeof AuthenticatedTimestampConverterRoute
  AuthenticatedUrlEncoderRoute: typeof AuthenticatedUrlEncoderRoute
  AuthenticatedUuidGeneratorRoute: typeof AuthenticatedUuidGeneratorRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBase64Route: AuthenticatedBase64Route,
  AuthenticatedBookmarksRoute: AuthenticatedBookmarksRoute,
  AuthenticatedColorConverterRoute: AuthenticatedColorConverterRoute,
  AuthenticatedDevBoardRoute: AuthenticatedDevBoardRoute,
  AuthenticatedDiffToolRoute: AuthenticatedDiffToolRoute,
  AuthenticatedFileValidatorRoute: AuthenticatedFileValidatorRoute,
  AuthenticatedFormatConverterRoute: AuthenticatedFormatConverterRoute,
  AuthenticatedHashGeneratorRoute: AuthenticatedHashGeneratorRoute,
  AuthenticatedHtmlEntitiesRoute: AuthenticatedHtmlEntitiesRoute,
  AuthenticatedHttpTesterRoute: AuthenticatedHttpTesterRoute,
  AuthenticatedImageToolsRoute: AuthenticatedImageToolsRoute,
  AuthenticatedJsonFormatterRoute: AuthenticatedJsonFormatterRoute,
  AuthenticatedJsonToTypescriptRoute: AuthenticatedJsonToTypescriptRoute,
  AuthenticatedJwtDecoderRoute: AuthenticatedJwtDecoderRoute,
  AuthenticatedLoremIpsumRoute: AuthenticatedLoremIpsumRoute,
  AuthenticatedQrGeneratorRoute: AuthenticatedQrGeneratorRoute,
  AuthenticatedRegexTesterRoute: AuthenticatedRegexTesterRoute,
  AuthenticatedTextManipulatorRoute: AuthenticatedTextManipulatorRoute,
  AuthenticatedTimestampConverterRoute: AuthenticatedTimestampConverterRoute,
  AuthenticatedUrlEncoderRoute: AuthenticatedUrlEncoderRoute,
  AuthenticatedUuidGeneratorRoute: AuthenticatedUuidGeneratorRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
