import {
  LucideIcon,
  Braces,
  Fingerprint,
  Binary,
  Clock,
  Palette,
  KeyRound,
  Regex,
  Hash,
  FileCheck,
  QrCode,
  Type,
  Link,
  ArrowRightLeft,
  GitCompare,
  TextQuote,
  FileCode,
  Code2,
  Globe,
  Bookmark,
  NotebookText,
  ImageIcon,
  Columns3,
  Dices,
  Webhook,
} from "lucide-react";

export interface ToolDef {
  id: string;
  path: string;
  name: string;
  description: string;
  icon: LucideIcon;
  category: string;
}

// Sidebar groups by first category appearance; keep high-value tools first.
export const tools: ToolDef[] = [
  {
    id: "dev-board",
    path: "/dev-board",
    name: "Dev Board",
    description: "Kanban board with auto time tracking for dev tasks",
    icon: Columns3,
    category: "Productivity",
  },
  {
    id: "bookmarks",
    path: "/bookmarks",
    name: "Bookmarks",
    description: "Save and organize documentation, repos, and articles",
    icon: Bookmark,
    category: "Resources",
  },
  {
    id: "resources",
    path: "/resources",
    name: "Resources",
    description: "Save notes, prompts, snippets, and reusable configs",
    icon: NotebookText,
    category: "Resources",
  },
  {
    id: "json-formatter",
    path: "/json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON",
    icon: Braces,
    category: "Data",
  },
  {
    id: "http-tester",
    path: "/http-tester",
    name: "HTTP Tester",
    description: "Send HTTP requests and inspect responses (no CORS)",
    icon: Globe,
    category: "Network",
  },
  {
    id: "webhook-inspector",
    path: "/webhook-inspector",
    name: "Webhook Inspector",
    description: "Create temporary URLs that capture and inspect incoming HTTP requests",
    icon: Webhook,
    category: "Network",
  },
  {
    id: "jwt-decoder",
    path: "/jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JWT header and payload",
    icon: KeyRound,
    category: "Decoders",
  },
  {
    id: "regex-tester",
    path: "/regex-tester",
    name: "Regex Tester",
    description: "Test regex patterns with live highlighting and match details",
    icon: Regex,
    category: "Testers",
  },
  {
    id: "base64",
    path: "/base64",
    name: "Base64",
    description: "Encode and decode Base64 with UTF-8 support",
    icon: Binary,
    category: "Encoders",
  },
  {
    id: "url-encoder",
    path: "/url-encoder",
    name: "URL Encoder",
    description: "Encode and decode URL components with percent-encoding",
    icon: Link,
    category: "Encoders",
  },
  {
    id: "html-entities",
    path: "/html-entities",
    name: "HTML Entities",
    description: "Encode and decode HTML entities (named, decimal, hex)",
    icon: Code2,
    category: "Encoders",
  },
  {
    id: "format-converter",
    path: "/format-converter",
    name: "Format Converter",
    description: "Convert between JSON, YAML, TOML, and more",
    icon: ArrowRightLeft,
    category: "Converters",
  },
  {
    id: "json-to-typescript",
    path: "/json-to-typescript",
    name: "JSON to TypeScript",
    description: "Infer TypeScript interfaces or types from JSON",
    icon: FileCode,
    category: "Converters",
  },
  {
    id: "timestamp-converter",
    path: "/timestamp-converter",
    name: "Timestamp Converter",
    description: "Convert between Unix timestamps and human-readable dates",
    icon: Clock,
    category: "Converters",
  },
  {
    id: "color-converter",
    path: "/color-converter",
    name: "Color Converter",
    description: "Convert between HEX, RGB, HSL, and OKLCH",
    icon: Palette,
    category: "Converters",
  },
  {
    id: "diff-tool",
    path: "/diff-tool",
    name: "Diff Tool",
    description: "Compare two texts and highlight line-by-line differences",
    icon: GitCompare,
    category: "Text",
  },
  {
    id: "text-manipulator",
    path: "/text-manipulator",
    name: "Text Manipulator",
    description: "Transform text: case convert, sort, dedupe, and more",
    icon: Type,
    category: "Text",
  },
  {
    id: "lorem-ipsum",
    path: "/lorem-ipsum",
    name: "Lorem Ipsum",
    description: "Generate placeholder text in plain, HTML, Markdown, or JSON",
    icon: TextQuote,
    category: "Text",
  },
  {
    id: "uuid-generator",
    path: "/uuid-generator",
    name: "UUID Generator",
    description: "Generate v4 and v7 UUIDs",
    icon: Fingerprint,
    category: "Generators",
  },
  {
    id: "hash-generator",
    path: "/hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, SHA-384, and SHA-512 hashes",
    icon: Hash,
    category: "Generators",
  },
  {
    id: "mock-data-generator",
    path: "/mock-data-generator",
    name: "Mock Data Generator",
    description: "Generate fake JSON test data from a custom or preset schema",
    icon: Dices,
    category: "Generators",
  },
  {
    id: "qr-generator",
    path: "/qr-generator",
    name: "QR Generator",
    description: "Generate QR codes with customizable size, colors, and error correction",
    icon: QrCode,
    category: "Generators",
  },
  {
    id: "file-validator",
    path: "/file-validator",
    name: "File Validator",
    description: "Calculate file hashes and verify integrity",
    icon: FileCheck,
    category: "Validators",
  },
  {
    id: "image-tools",
    path: "/image-tools",
    name: "Image Tools",
    description: "Compress and convert PNG, JPG, and WebP images offline",
    icon: ImageIcon,
    category: "Media",
  },
];

export function getToolByPath(path: string): ToolDef | undefined {
  return tools.find((t) => t.path === path) ?? tools.find((t) => path.startsWith(`${t.path}/`));
}
